version: '3.8'

services:
  data-store-service:
    build: ./data_store_service
    ports:
      - 5001:5000
  
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - 1883:1883
      
  
  data-store-agent:
    build: ./data_ingest_service
    ports:
      - 8080:80
      
  
